import { Category } from "./types";

export const CATEGORY_LABEL: Record<Category, string> = {
  fruits: "Fruits",
  vegetables: "Vegetables",
  meat_seafood: "Meat & Seafood",
  dairy_eggs: "Dairy & Eggs",
  rice: "Rice",
  oils: "Oils",
  grains: "Grains",
  pulses: "Pulses",
  spices: "Spices",
  sugar: "Sugar",
  tea_coffee: "Tea & Coffee",
  bakery: "Bakery",
  instant_food: "Instant Food",
  snacks: "Snacks",
  personal_care: "Personal Care",
  household: "Household",
  dining_out: "Dining Out",
  transport: "Transport",
  utilities: "Utilities",
  rent: "Rent",
  entertainment: "Entertainment",
  subscriptions: "Subscriptions",
  shopping: "Shopping",
  health: "Health",
  travel: "Travel",
  transfers: "Transfers",
  fees: "Fees",
  gifts: "Gifts",
  other: "Other",
};
